export default {
  "glyphs": [
    {
      "name": "warn",
    }, {
      "name": "warn-full"
    }, {
      "name": "user"
    }, {
      "name": "video"
    }, {
      "name": "textarea"
    }, {
      "name": "triangle-arrow"
    }, {
      "name": "tag"
    }, {
      "name": "success"
    }, {
      "name": "success-line"
    }, {
      "name": "star"
    }, {
      "name": "star-full"
    }, {
      "name": "shop-car"
    }, {
      "name": "sound-close"
    }, {
      "name": "sound"
    }, {
      "name": "share"
    }, {
      "name": "share"
    }, {
      "name": "share-full"
    }, {
      "name": "rule"
    }, {
      "name": "replay"
    }, {
      "name": "refresh"
    }, {
      "name": "qrcode"
    }, {
      "name": "question-mark"
    }, {
      "name": "qq"
    }, {
      "name": "plus-icon"
    }, {
      "name": "plus-mark"
    }, {
      "name": "money"
    }, {
      "name": "multi-user"
    }, {
      "name": "plus-circle"
    }, {
      "name": "phone"
    }, {
      "name": "loading-gray"
    }, {
      "name": "loading"
    }, {
      "name": "map"
    }, {
      "name": "money-full"
    }, {
      "name": "light"
    }, {
      "name": "lbs"
    }, {
      "name": "lbs-line"
    }, {
      "name": "image"
    }, {
      "name": "lbs-full"
    }, {
      "name": "heart"
    }, {
      "name": "good"
    }, {
      "name": "heart-full"
    }, {
      "name": "good-full"
    }, {
      "name": "gift"
    }, {
      "name": "gift-light"
    }, {
      "name": "fire"
    }, {
      "name": "file"
    }, {
      "name": "double-arrow-right"
    }, {
      "name": "coupon"
    }, {
      "name": "crown"
    }, {
      "name": "del"
    }, {
      "name": "close"
    }, {
      "name": "close-simple"
    }, {
      "name": "close-special"
    }, {
      "name": "close-line"
    }, {
      "name": "clock"
    }, {
      "name": "clock-full"
    }, {
      "name": "circle-arrow"
    }, {
      "name": "cart"
    }, {
      "name": "camera"
    }, {
      "name": "change"
    }, {
      "name": "cart-rect"
    }, {
      "name": "calendar"
    }, {
      "name": "cart-full"
    }, {
      "name": "backtop"
    }, {
      "name": "buynow"
    }, {
      "name": "arrow-go"
    }, {
      "name": "arrow-normal"
    }, {
      "name": "arrow-down"
    }, {
      "name": "arrow-right"
    }, {
      "name": "arrow-big"
    }, {
      "name": "arrow-back"
    }, {
      "name": "arrow-full"
    }
  ]
}
